theme: jekyll-theme-minimal
title: Rising Engineers Advanced Challenge 2019
description: REACh is a non-stop 24-hour competition, where students will get the opportunity to be drafted by some of the leading engineering companies in the world. The competition last 24-hours, and in this time period, students will design, build, and market a project from scratch.

![REACh Banner](https://github.com/lrg002/lrg002.github.io/blob/images-1/REACh%202019%20Banner.png)
